apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Sample Website</title>
    </head>
    <body>
        <h1>Welcome to the Website!</h1>
        <p>This website is deployed using Argo CD in MicroK8s</p>
        <br>
        <p> Testing Automatic Sync; changes to be reflected </p>
    </body>
    </html>
