apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Kemthur-Suraj/argocd-website.git"
    targetRevision: HEAD
    path: helm/website
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
